### PR TITLE
Removed obsolete dependency

### PR DESCRIPTION
**Pull request by jantanis**
Package.mscorlib is obsolete and conflicts with the default mscorlib library.

### CODE REVIEW

**Comment by jantanis** [comment]
Can you please publish a new nuget package?

**Comment by speed78** [comment]
Yes Jan, I will publish asap, but a the moment I'm in holidays. I'm sorry

Il 14 Ago 2017 08:04, "Jan Tanis" <notifications@github.com> ha scritto:

**Comment by jantanis** [comment]
Have a nice holiday!

**Comment by speed78** [comment]
Tnx :-)

Il 14 Ago 2017 13:05, "Jan Tanis" <notifications@github.com> ha scritto:

**Pull request merged**
